"""Replay the previously qualified InternLM dependency tree, before importing it.

This performs no installation and does not modify the shared container. The
historical manifest is pinned independently of caller-supplied configuration.
Run on an allocated compute node, not the login node.
"""
import argparse
import json
import os
from pathlib import Path

from ..io import read, sha256
from .schema import require

SPEC_SHA256 = "54419278650427638ce329c502c4de40d5736d17cfbfd6d4ef0224cdbe63d01f"
RUNTIME = Path("/work/projects/polyullm/xxj/PALS/src/pals-runtime-internlm3471-20260921-v2")
SPEC = Path("/work/projects/polyullm/xxj/PALS/runs/20261003-internlm-fivebench-e1e2-v1/spec.json")


def verify_tree(runtime, files):
    require(runtime.resolve(strict=True) == runtime, "compatibility runtime symlink")
    require(bool(files), "empty compatibility manifest")
    for name, expected in files.items():
        relative = Path(name)
        require(not relative.is_absolute() and ".." not in relative.parts,
                "unsafe dependency manifest path")
        path = runtime / relative
        require(path.resolve(strict=True) == path and path.is_file(), "unsafe dependency file")
        require(sha256(path) == expected, "dependency changed: " + name)
    # Extra importable files could shadow a pinned module. Generated bytecode is
    # not accepted either: the legacy runtime is mounted read-only, with -B.
    actual = {str(p.relative_to(runtime)) for p in runtime.rglob("*") if p.is_file()}
    require(actual == set(files), "extra or missing dependency files")
    return len(files)


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--spec", type=Path, required=True)
    p.add_argument("--runtime", type=Path, required=True)
    args = p.parse_args()
    require(bool(os.environ.get("SLURM_JOB_ID")), "compute allocation required")
    require(args.runtime == RUNTIME and args.spec == SPEC and args.spec.resolve(strict=True) == SPEC,
            "unapproved compatibility runtime")
    require(sha256(args.spec) == SPEC_SHA256, "historical compatibility spec changed")
    spec = read(args.spec)
    require(spec["runtime"] == str(RUNTIME), "historical runtime differs")
    count = verify_tree(args.runtime, spec["runtime_files"])
    print(json.dumps({"status": "PASS", "runtime": str(RUNTIME), "files_verified": count,
                      "spec_sha256": SPEC_SHA256}), flush=True)


if __name__ == "__main__":
    main()
